/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import {
  ContractBase,
  IContractConstructor,
  IEmptyClient,
} from "./contractContextBase";
import { BlottoClient, BlottoQueryClient } from "./Blotto.client";
export class Blotto extends ContractBase<
  BlottoClient,
  BlottoQueryClient,
  IEmptyClient
> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient,
  }: IContractConstructor) {
    super(
      address,
      cosmWasmClient,
      signingCosmWasmClient,
      BlottoClient,
      BlottoQueryClient,
      undefined
    );
  }
}
