/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import {
  CosmWasmClient,
  SigningCosmWasmClient,
} from "@cosmjs/cosmwasm-stargate";
import {
  IQueryClientProvider,
  ISigningClientProvider,
  IMessageComposerProvider,
} from "./contractContextBase";
import { BlottoQueryClient } from "./Blotto.client";
import { BlottoClient } from "./Blotto.client";
import { Blotto } from "./Blotto.provider";
export interface IContractsContext {
  blotto: IQueryClientProvider<BlottoQueryClient> &
    ISigningClientProvider<BlottoClient>;
}
export const getProviders = (
  address?: string,
  cosmWasmClient?: CosmWasmClient,
  signingCosmWasmClient?: SigningCosmWasmClient
) => ({
  blotto: new Blotto({
    address,
    cosmWasmClient,
    signingCosmWasmClient,
  }),
});
