/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Blotto.types";
import * as _1 from "./Blotto.client";
import * as _2 from "./Blotto.react-query";
export namespace contracts {
  export const Blotto = { ..._0,
    ..._1,
    ..._2
  };
}